# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cone < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.13/cone-v0.0.13-darwin-amd64.zip"
      sha256 "acddae2fe453402e350bb563e99b7595c3c4e9a4ac0a0a3a542d784c615660ce"

      def install
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.13/cone-v0.0.13-darwin-arm64.zip"
      sha256 "4ca33ca120ee4d87efb7f271540cb435014b6793f7bfc2db571637799ad3e6ed"

      def install
        bin.install "cone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.13/cone-v0.0.13-linux-arm64.tar.gz"
      sha256 "32f1c3efbfd0a914237e528b0275f41a9468a931ffcf18e9e394bc7d75e0c89b"

      def install
        bin.install "cone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.13/cone-v0.0.13-linux-amd64.tar.gz"
      sha256 "1a2f79b2e5937f9a736f8dc5e8fbf56edf1bd6c9dbda4a21e959000e9c663404"

      def install
        bin.install "cone"
      end
    end
  end

  test do
    system "#{bin}/cone -v"
  end
end
