# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cone < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.10/cone-v0.0.10-darwin-amd64.zip"
      sha256 "27ba955f2f63c162e31e211cf3fd95b7c2bc96d30b59e33f65206f04ee916489"

      def install
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.10/cone-v0.0.10-darwin-arm64.zip"
      sha256 "0edeff68d789e9a1b656f138b76313e9e56718d1630b30ebaa2edd51f9707e46"

      def install
        bin.install "cone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.10/cone-v0.0.10-linux-arm64.tar.gz"
      sha256 "18541f55e0ff16d016a71c4f75f11e0f90069973b60ead29a388fbeaac6f1563"

      def install
        bin.install "cone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/cone/releases/download/v0.0.10/cone-v0.0.10-linux-amd64.tar.gz"
      sha256 "be4ce79391a0c0d82ddd0864dc0ed163bdc8e610bcdbda082c133a3f2a4fb9dc"

      def install
        bin.install "cone"
      end
    end
  end

  test do
    system "#{bin}/cone -v"
  end
end
